name: Build and Push Standard Docker Image

on:
  repository_dispatch:
    types: [caddy-release, build-standard-image]
  workflow_dispatch:
    inputs:
      build_version:
        description: "Caddy version to build (without v prefix, e.g., 2.8.0)"
        required: false

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert Repository Owner to Lowercase
        run: |
          echo "GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
          REPO_OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV

      - name: Set version if empty
        id: set_version
        run: |
          if [ -n "${{ github.event.inputs.build_version }}" ]; then
            VERSION=$(echo "${{ github.event.inputs.build_version }}" | sed 's/^v//')
          elif [ -n "${{ github.event.client_payload.latest_version }}" ]; then
            VERSION=$(echo "${{ github.event.client_payload.latest_version }}" | sed 's/^v//')
          else
            VERSION=$(cat version.json | jq -r '.version' | sed 's/^v//')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check Caddy version availability
        id: check_version
        run: |
          RETRY_COUNT=0
          MAX_RETRIES=5
          SLEEP_INTERVAL=3600  # 1 hour in seconds

          check_availability() {
            AVAILABLE_BUILDER=$(curl -sL https://hub.docker.com/v2/repositories/library/caddy/tags/${{ env.VERSION }}-builder | jq -r '.name')
            AVAILABLE_BASE=$(curl -sL https://hub.docker.com/v2/repositories/library/caddy/tags/${{ env.VERSION }} | jq -r '.name')
            if [ "$AVAILABLE_BUILDER" = "${{ env.VERSION }}-builder" ] && [ "$AVAILABLE_BASE" = "${{ env.VERSION }}" ]; then
              return 0
            else
              return 1
            fi
          }

          until check_availability; do

            if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
              echo "Caddy version ${{ env.VERSION }}-builder or ${{ env.VERSION }} is not available after $MAX_RETRIES retries. Setting environment variable to trigger job again."
              echo "DEPENDENCIES_AVAILABILITY=false" >> $GITHUB_ENV
              break
            fi
            echo "Caddy version ${{ env.VERSION }}-builder or ${{ env.VERSION }} is not available. Retrying in $SLEEP_INTERVAL seconds..."
            sleep $SLEEP_INTERVAL
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done

          if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
            echo "DEPENDENCIES_AVAILABILITY=true" >> $GITHUB_ENV
          fi

      - name: Trigger Build Workflow
        if: env.DEPENDENCIES_AVAILABILITY == 'false'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'build-standard-image',
            })

      - name: Build and push Docker image (standard)
        if: env.DEPENDENCIES_AVAILABILITY == 'true'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            CADDY_VERSION=${{ env.VERSION }}
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/caddy-cloudflare-webdav:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_OWNER }}/caddy-cloudflare-webdav:latest

      - name: Clean up Docker images
        if: env.DEPENDENCIES_AVAILABILITY == 'true'
        run: |
          docker rmi ghcr.io/${{ env.REPO_OWNER }}/caddy-cloudflare-webdav:${{ env.VERSION }} || true
          docker builder prune --force

      - name: Create GitHub Release
        if: env.DEPENDENCIES_AVAILABILITY == 'true'
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Caddy v${{ env.VERSION }}"
          body: "New Caddy release detected. See the full release notes [here](https://github.com/caddyserver/caddy/releases/tag/v${{ env.VERSION }})."
          draft: false
          prerelease: false
